codes:
  ntYpos: 'ae givercbook LEGENDARY %player% 4'
  rSdIsH: 'es give %player% Cod 2'
  FOrkiR: 'rs give %player% 1 Resistance'
  NceNTU: 'cmi money give %player% 900'

used:
  ntYpos:
    - 'Никто'
  rSdIsH:
    - 'Никто'
  FOrkiR:
    - 'Никто'
  NceNTU:
    - 'Никто'